Fix Platform.POLLEN import error
- Removed Platform.POLLEN from PLATFORMS list (doesn't exist in HA)
- This fixes: AttributeError: type object 'EntityPlatforms' has no attribute 'POLLEN'